--
-- CWM Scripture Library - Uninstall SQL (intentionally empty)
--
-- This file used to DROP the three bible tables. It must never do that again:
-- Joomla's LibraryAdapter uninstalls the installed library before writing the
-- new one, so this file ran on every UPDATE and destroyed every locally
-- downloaded translation (#__bsms_bible_verses can hold hundreds of MB the
-- site owner downloaded by hand). plg_system_proclaim neutralises this file on
-- sight for the same reason.
--
-- The manifest no longer references this file at all; it is kept as a no-op so
-- that sites still carrying an older manifest -- which does reference it -- run
-- nothing instead of failing to find it.
--
-- Real table removal lives in script.php::uninstall(), which only drops when
-- the library is genuinely being removed and no consumer (com_proclaim,
-- plg_content_scripturelinks) still shares the tables.
--
-- Do not reintroduce DROP TABLE statements here.
--