--
-- CWM Scripture Library - Uninstall SQL (intentionally empty)
--
-- Joomla runs a library's uninstall SQL on every update, not only on a real
-- uninstall. The DROP TABLE statements this file used to hold therefore wiped
-- every downloaded Bible translation each time lib_cwmscripture was upgraded,
-- so they have been removed. plg_system_proclaim neutralises this file on
-- sight for the same reason.
--
-- Nothing currently drops the tables. script.php::uninstall() is a no-op, so a
-- genuine uninstall leaves #__bsms_bible_translations, #__bsms_bible_verses and
-- #__bsms_scripture_cache behind. That is deliberate for now: the tables are
-- shared with Proclaim, so removal has to be conditional on Proclaim not being
-- installed rather than unconditional. Tracked in issue #17.
--
-- Do not reintroduce DROP TABLE statements here.
--
